# Generated by Django 4.1.7 on 2023-04-07 09:35

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('data_added', models.TimeField(auto_now_add=True)),
                ('data_update', models.TimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=200, populate_from='title', unique=True)),
            ],
            options={
                'verbose_name': 'BlogPost',
                'verbose_name_plural': 'BlogPost',
            },
        ),
        migrations.CreateModel(
            name='Fakemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
            ],
        ),
    ]
